import ProjectDescription

let workspace = Workspace(
    name: "LoopLife",
    projects: [
        "LoopLife"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
