import ProjectDescription

let workspace = Workspace(
    name: "Tempoo",
    projects: [
        "Tempoo"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
