import ProjectDescription

let workspace = Workspace(
    name: "iRings",
    projects: [
        "iRings"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
