opt_in_rules:
  - class_delegate_protocol
  - cyclomatic_complexity
  - empty_enum_arguments
  - file_length
  - force_cast
  - force_unwrapping
  - function_body_length
  - custom_rules
  - weak_delegate
  - overridden_super_call
  - pattern_matching_keywords
  - superfluous_disable_command
disabled_rules:
  - identifier_name
  - file_length
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - LoopLife
  - LoopLifeCore
  - LoopLifeUI
  - LoopLifeResources
  - Features
  - Services
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
force_cast: warning # implicitly


